---
- name: add homebrew taps
  homebrew_tap: >
    name={{item}}
  with_items:
    - fisherman/tap
    - railwaycat/emacsmacport
    - johanhaleby/kubetail

- name: install homebrew packages
  homebrew: >
    name={{item}}
    state=present
  with_items:
    - ack
    - carthage
    - cloc
    - coreutils
    - curl
    - dnsmasq
    - fish
    - fisherman
    - fzf
    - git
    - gpg
    - graphviz
    - heroku
    - hledger
    - htop
    - hugo
    - ispell
    - isync
    - jq
    - kubetail
    - libmemcached
    - macvim
    - memcached
    - mercurial
    - msmtp
    - mysql
    - par
    - pgbouncer
    - postgresql
    - prometheus
    - protobuf
    - pyenv
    - readline
    - redis
    - rlwrap
    - sbt
    - scala
    - telnet
    - terminal-notifier
    - the_silver_searcher
    - tmux
    - tree
    - vim
    - watch
    - watchman
    - yarn

- name: install mu with emacs support
  homebrew: >-
    name=mu
    state=present
    install_options=with-emacs

- name: install emacs-mac from homebrew
  homebrew: >-
    name=emacs-mac
    state=present
    install_options=with-official-icon

- name: install reattach-to-user-namespace from homebrew
  homebrew: >-
    name=reattach-to-user-namespace
    install_options=wrap-pbcopy-and-pbpaste
