---
- name: add homebrew taps
  homebrew_tap: >
    name={{item}}
  with_items:
    - fisherman/tap
    - railwaycat/emacsmacport

- name: install homebrew packages
  homebrew: >
    name={{item}}
    state=present
  with_items:
    - ack
    - cloc
    - coreutils
    - curl
    - fish
    - fisherman
    - git
    - graphviz
    - ispell
    - jq
    - keybase
    - macvim
    - memcached
    - notmuch
    - postgresql
    - protobuf
    - readline
    - rlwrap
    - roswell
    - sbt
    - scala
    - terminal-notifier
    - the_silver_searcher
    - tmux

- name: install emacs-mac from homebrew
  homebrew: >-
    name=emacs-mac
    state=present
    install_options=with-official-icon

- name: install reattach-to-user-namespace from homebrew
  homebrew: >-
    name=reattach-to-user-namespace
    install_options=wrap-pbcopy-and-pbpaste
