---
- name: setup homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - denji/nginx

- name: install homebrew packages
  homebrew:
    name:
      - ack
      - argon2
      - carthage
      - cloc
      - coreutils
      - curl
      - dnsmasq
      - emacs
      - fish
      - git
      - git-lfs
      - gpg
      - graphviz
      - hledger
      - htop
      - hugo
      - ispell
      - isync
      - jq
      - libmemcached
      - memcached
      - mercurial
      - msmtp
      - mysql
      - nginx-full
      - par
      - pinentry-mac
      - postgresql
      - prometheus
      - readline
      - redis
      - rlwrap
      - tarsnap
      - telnet
      - terminal-notifier
      - the_silver_searcher
      - tmux
      - tree
      - vim
      - watch
      - watchman
      - ykman
    state: present

- name: install mu with emacs support
  homebrew:
    name: mu
    state: present
    install_options: HEAD

- name: install reattach-to-user-namespace from homebrew
  homebrew:
    name: reattach-to-user-namespace
    install_options: HEAD
