---
- name: install stack
  homebrew:
    name={{item}} state=present
  with_items:
    - haskell-stack

- name: ensure stack directories exist
  file: >-
    path=~/.stack/global
    state=directory
    recurse=true

- name: configure stack
  copy: >-
    src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: "stack-global.yaml", dest: "~/.stack/global/stack.yaml"}
    - {src: "config.yaml", dest: "~/.stack/config.yaml"}
