---
- name: install or upgrade stack
  shell: >-
    if [ ! $(command -v stack 2> /dev/null) ]; then
      curl -sSL https://get.haskellstack.org/ | sh
    fi

- name: configure stack
  copy: >-
    src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: "stack-global.yaml", dest: "~/.stack/global/stack.yaml"}
    - {src: "config.yaml", dest: "~/.stack/config.yaml"}
