---
- name: ensure mail dirs are present
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - ~/Mail
    - ~/Mail/business
    - ~/Mail/personal-archive
    - ~/Mail/personal
    - ~/Mail/work-blockfraud
    - ~/Mail/work-gamemine
    - ~/Mail/work-remoteonly
