---
- name: install cask packages
  homebrew_cask:
    name:
      - 1password
      - amethyst
      - dash
      - docker
      - firefox
      - java
      - mactex
      - opensc
      - screenflow
      - skype
      - spotify
      - steam
      - telegram
      - transmission
      - vlc
    state: present
