---
- name: install cask packages
  homebrew_cask: >
    name={{item}}
    state=present
  with_items:
    - 1password
    - alfred
    - dash
    - dropbox
    - firefox
    - google-chrome
    - iterm2
    - karabiner
    - keka
    - moom
    - little-snitch
    - screenflow
    - skype
    - slack
    - spotify
    - transmission
    - vlc
