---
- name: make Fish the default shell
  user: >
    name=bogdan
    shell=/usr/local/bin/fish
  become: yes

- name: clone dotfiles repo
  shell: >
    if [ ! -d {{sandbox_path}}/dotfiles ]; then
      git clone git@github.com:Bogdanp/dotfiles.git {{sandbox_path}}/dotfiles
    fi

- name: clone .emacs.d repo
  shell: >
    if [ ! -d ~/.emacs.d ]; then
      git clone git@github.com:Bogdanp/.emacs.d.git ~/.emacs.d
      cd ~/.emacs.d && git submodule update --init
    fi

- name: ensure fish directories exist
  file: >-
    path=~/.config/fish/functions
    state=directory
    recurse=true

- name: link dotfiles
  file: >-
    src={{sandbox_path}}/dotfiles{{item.src}}
    dest={{item.dest}}
    state=link
  with_items:
    - {src: "/fish/config.fish", dest: "~/.config/fish/config.fish"}
    - {src: "/fish/functions/docker-cleanup.fish", dest: "~/.config/fish/functions/docker-cleanup.fish"}
    - {src: "/fish/functions/ec.fish", dest: "~/.config/fish/functions/ec.fish"}
    - {src: "/fish/functions/ef.fish", dest: "~/.config/fish/functions/ef.fish"}
    - {src: "/fish/functions/fish_greeting.fish", dest: "~/.config/fish/functions/fish_greeting.fish"}
    - {src: "/fish/functions/fish_prompt.fish", dest: "~/.config/fish/functions/fish_prompt.fish"}
    - {src: "/fish/functions/forward-fish.fish", dest: "~/.config/fish/functions/forward-fish.fish"}
    - {src: "/fish/functions/gcloud-switch-project.fish", dest: "~/.config/fish/functions/gcloud-switch-project.fish"}
    - {src: "/fish/functions/gpg_backup.fish", dest: "~/.config/fish/functions/gpg_backup.fish"}
    - {src: "/fish/functions/gpg_restore.fish", dest: "~/.config/fish/functions/gpg_restore.fish"}
    - {src: "/fish/functions/instenv.fish", dest: "~/.config/fish/functions/instenv.fish"}
    - {src: "/fish/functions/workon.fish", dest: "~/.config/fish/functions/workon.fish"}
    - {src: "/fish/functions/wf.fish", dest: "~/.config/fish/functions/wf.fish"}
    - {src: "/bashrc", dest: "~/.bashrc"}
    - {src: "/hgrc", dest: "~/.hgrc"}
    - {src: "/mbsyncrc", dest: "~/.mbsyncrc"}
    - {src: "/msmtprc", dest: "~/.msmtprc"}
    - {src: "/psqlrc", dest: "~/.psqlrc"}
    - {src: "/tmux", dest: "~/.tmux"}
    - {src: "/tmux.conf", dest: "~/.tmux.conf"}
    - {src: "/vimrc", dest: "~/.vimrc"}

- name: install fish plugins
  shell: fisher install {{item}}; or true
  args:
    executable: /usr/local/bin/fish
  with_items:
    - edc/bass
    - fzf
    - nvm
