---
- name: get brew prefix
  shell: brew --prefix
  register: brew_prefix

- name: add Dinghy tap
  homebrew_tap: >
    name=codekitchen/dinghy

- name: install Docker packages
  homebrew: >
    name={{item}}
    state=present
  with_items:
    - docker
    - docker-machine
    - dinghy
