---
- name: get brew prefix
  shell: brew --prefix
  register: brew_prefix

- name: add Dinghy tap
  homebrew_tap: >
    name=codekitchen/dinghy

- name: install Docker packages
  homebrew: >
    name={{item}}
    state=present
  with_items:
    - xhyve
    - docker
    - docker-machine
    - docker-machine-driver-xhyve
    - dinghy

- name: configure {docker-machine-driver,}xhyve permissions
  become: true
  become_user: root
  file: >
    path={{brew_prefix.stdout}}/opt/{{item}}/bin/{{item}}
    owner=root
    group=wheel
    mode=u+s
  with_items:
    - xhyve
    - docker-machine-driver-xhyve
